version: '3.8'

services:
  todo-app:
    image: todo-app
    command: ./server/scripts/wait-for-postgres.sh todo-app-postgres ./todo-app
    ports:
      - "8000:8000"
    depends_on:
      - todo-app-postgres
    networks:
      todo-app.net:
    environment:
      - PG_HOST=todo-app-postgres
      - PG_DATABASENAME=postgres
      - PR_USERNAME=postgres
      - PG_PASSWORD=qwerty
      - PG_PORT=5432
      - PG_SSL_MODE=disable

  todo-app-postgres:
    hostname: todo-app-postgres
    restart: always
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
    networks:
      todo-app.net:


#  migrate:
#    image: migrate/migrate
#    networks:
#      todo-app.net:
#    links:
#      - todo-app-postgres
#    depends_on:
#      - todo-app-postgres
#    volumes:
#      - .:/migrations
#    command:
#      [ "-path", "./migrations", "-database",  "postgres://postgres:qwerty@database:5432/postgres?sslmode=disable", "up", "3" ]

volumes:
  pg_data:
networks:
  todo-app.net: