port: "8000"

db:
  username: "postgres"
  host: "todo-app-postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

postgres:
  usersTable: "users"
  todoListsTable: "todo_lists"
  usersListsTable: "users_lists"
  todoItemsTable: "todo_items"
  listsItemsTable: "lists_items"